import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="w-full h-screen flex justify-center items-center">
      <Head>
        <title>chendap Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          This is{" "}
          <Link href="./blog" className="underline-offset-1">
            My Blog
          </Link>
        </h1>
      </main>
    </div>
  );
};

export default Home;
